create table public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  state text,
  district text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

create table public.disease_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  disease_name text not null,
  confidence double precision not null,
  report text not null,
  state text,
  district text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

create index disease_reports_user_created_at_idx
  on public.disease_reports (user_id, created_at desc);

create index disease_reports_district_created_at_idx
  on public.disease_reports (district, created_at desc);